### ISSUE TITLE
请教：关于安卓嵌入V8的问题

### ISSUE THREAD

**Issue by youngwind** [LiuHongtao/JustDraw#1]
hi, LiuHongtao:
     最近我在研究“如何在安卓上使用V8引擎”这个问题，看到你的[这篇文章](https://neyoufan.github.io/2016/12/23/android/Android%20Js%E5%BC%95%E6%93%8E/%E5%9C%A8Android%E4%B8%8A%E4%BD%BF%E7%94%A8JS%E5%BC%95%E6%93%8E%E6%98%AF%E4%B8%80%E7%A7%8D%E4%BB%80%E4%B9%88%E6%A0%B7%E7%9A%84%E4%BD%93%E9%AA%8C%EF%BC%9F/)，收获良多，非常感谢。
我有一些更进一步的问题想向你请教，不知是否方便邮件联系？
如果不方便在这里暴露你的邮箱，你也可以直接给我发邮件，我的邮箱：540506594@qq.com
期待你的回复。

**Comment by LiuHongtao** [comment]
已经给你邮件了，谢谢！
